keyNotesList:
  - id: 1
    img: KeynoteImgs/thais.jfif
    nome: Thais Viana
    descricao: "Não dava para fazer o evento no Rio sem ela. A Thais é simplesmente uma das maiores referências da nossa comunidade. São mais de dez anos de dedicação na PyLadies e na PythOnRio, além de ter liderado a Python Brasil 2024 como Big Kahuna.\n\nQuem conhece sabe o quanto ela inspira: uma mulher que concilia o corre dos saberes técnicos, pós-graduação, liderança de comunidade e a maternidade. Não é à toa que recebeu o Prêmio Dorneles Treméa, que só oficializou o valor absurdo que ela entrega pra gente todos os dias.\n\nTer a Thais como keynote em casa vai ser incrível. E óbvio: para que ela e todas as mães e pais aproveitem o evento com tranquilidade, teremos um espaço para acolher os pequenos com todo o carinho."
    githubLink: null
    githubArroba: null
    linkedinLink: null
    linkedinArroba: null
    instagramLink: null
    instagramArroba: null
  - id: 2
    img: KeynoteImgs/nina.jpg
    nome: Nina da Hora
    descricao: "Cientista, pesquisadora e cria da Baixada, a Nina é uma das vozes mais potentes do país quando o assunto é divulgação científica, direitos digitais e a desconstrução da ética dos algoritmos de um jeito que todo mundo consegue entender. À frente do @instituto_dahora, transforma a forma como pensamos o futuro digital.\n\nNina tem a cara da comunidade Python e mostra que falar de tecnologia por aqui vai muito além de linhas de código: envolve responsabilidade social, inclusão e justiça."
    githubLink: null
    githubArroba: null
    linkedinLink: null
    linkedinArroba: null
    instagramLink: null
    instagramArroba: null
